---
title: "Relatório da implementação do algoritmo de compressão LZW através de Tries"
author: "Guilherme Buxbaum e Samuel Brum Martins"
format:
  html:
    code-fold: true
# bibliography: references.bib
---

# Introdução
## Compressão LZW

Esse repositório contém uma implementação, em python, do método de compressão Lempel-Ziv-Welch (LZW) que utiliza uma árvore trie como dicionário. Nessa implementação os arquivos de entrada são tratados como arquivos binários, o que permite sua utilização para a compressão de diversos tipos de arquivos. O algoritmo então utiliza o dicionário para auxiliar na transformação de sequências de bytes do binário do arquivo original em códigos de 9 a 16 bits, o que causa a redução de tamanho do arquivo. A grande vantagem deste método é a construção do dicionário ao mesmo tempo em que a compressão ou descompressão do arquivo é feita, o que faz ele se adaptar a cada um.

**Compressão:** 

A compressão com o algoritmo LZW começa com a inicialização do dicionário, que contém todos os 256 valores possíveis que um byte pode armazenar (0 a 255). À medida que os bytes do arquivo de entrada são lidos, o algoritmo constrói sequências de bytes e verifica se essas sequências estão no dicionário. Quando uma sequência não está no dicionário, o código da sequência anterior é escrito no arquivo de saída, e a nova sequência é adicionada ao dicionário com um novo código. O tamanho dos códigos pode variar entre 9 e 16 bits, conforme especificado pelo usuário. O primeiro byte do arquivo comprimido geralmente armazena o número de bits utilizado para os códigos.

**Descompresssão:** 

A descompressão com o algoritmo LZW começa com a leitura do primeiro byte do arquivo comprimido para determinar o número de bits utilizado para os códigos. O dicionário é então inicializado com todos os 256 valores possíveis que um byte pode armazenar (0 a 255). Os códigos são lidos sequencialmente do arquivo comprimido, e cada código é convertido de volta para a sequência de bytes correspondente usando o dicionário. Para cada código lido, a sequência de bytes correspondente é escrita no arquivo de saída. Se um código não estiver no dicionário (caso especial), ele é tratado de acordo com o algoritmo LZW. Novas sequências são adicionadas ao dicionário à medida que os códigos são processados, permitindo a reconstrução completa dos dados originais.

## Estrutura da implementação

A seguir segue a explicação sobre as principais estruturas e funções da implementação.

### Trie.py

Nessa implementação, o dicionário utilizado pelo algoritmo foi implementado através de uma árvore Trie, que está definida no arquivo **trie.py**. A árvore é construida com base nas palavras que queremos armazenar no dicionário, ou seja, sequências de bytes do arquivo de entrada, e contém os métodos para Inserção, Remoção e Pesquisa de palavras. Como as palavras inseridas são sequências de bytes, descer um nível na árvore representa o crescimento da palavra em 1 byte.

Os nós da Trie foram implementados na classe **Vertice**, que contém dois atributos. O atributo **filho** é um dicionário python que contém os vértices filhos de determinado vértice. Aqui, esse dicionário pode ter até 256 entradas (0 a 255), cada uma representando um dos possíveis valores para um byte. O outro atributo é "valor", que armazena o código para a palavra que o vértice simboliza.


### Compressor.py

A compressão de arquivos é feita pelo script "compressor.py". Que deve ser utilizado da seguinte forma:

```{sh}
python3 compressor.py arquivo_entrada.txt
```

**Parâmetros**

arquivo_entrada.txt: O arquivo que o usuário deseja comprimir

- --bits ou -b: Define o número máximo de bits para os códigos (entre 8 e 16). O padrão é 12.

- --stats ou -s: Ativa a coleta de estatísticas durante a compressão. As estatísticas serão salvas em um arquivo com a extensão .stats.

- --saida ou -o: Define o nome do arquivo de saída. Se não for especificado, o arquivo de saída terá o mesmo nome do arquivo de entrada com a extensão .lzw.

Para comprimir um arquivo exemplo.txt utilizando 12 bits para os códigos e coletar estatísticas, você pode usar o seguinte comando:

```{sh}
python3 compressor.py exemplo.txt --bits 12 --stats --saida exemplo_comprimido.lzw
```

Isso criará dois arquivos:

 - exemplo_comprimido.lzw: O arquivo comprimido.
 - exemplo_comprimido.lzw.stats: Arquivo JSON contendo as estatísticas da compressão.

**Estatísticas Coletadas**
Se a opção --stats for utilizada, o script coletará as seguintes estatísticas durante a compressão:

- momento: Tempo decorrido desde o início da compressão.
- tamanho_entrada: Tamanho do arquivo de entrada processado até o momento.
- tamanho_saida: Tamanho do arquivo de saída gerado até o momento.
- taxa_compressao: Taxa de compressão (tamanho do arquivo de saída / tamanho do arquivo de entrada).
- tamanho_dicionario: Número de entradas no dicionário.
- memoria_dicionario: Memória utilizada pelo dicionário.
- tempo_execucao: Tempo total de execução até o momento.

Essas estatísticas são salvas em um arquivo JSON com a extensão .stats.

O compressor funciona com qualquer tipo de arquivo, pois sua lógica está implementada em cima dos arquivos em binário. Assim, as palavras armazenadas no dicionário serão todas sequências de bytes.

A lógica da compressão está na função "comprimir", que recebe o arquivo a ser comprimido, o tamanho em bits dos códigos e um caminho para o arquivo de saída.

A função se inicia com a inicialização do dicionário, ou seja, inserimos na Trie todos os 256 valores possíveis que apenas um byte consegue armazenar (0 a 255). Na sequência, abrimos o arquivo a ser comprimido para leitura em modo binário, e o arquivo que iremos utilizar como saída para escrita em modo binário. 

O algoritmo segue da seguinte forma: começamos com uma palavra P inicialmente vazia e iteramos sobre todos os bytes do arquivo de entrada. A cada iteração concatenamos o byte lido com P e verificamos se o resultado está presente no dicionário, caso esteja, passamos ao próximo byte, caso contrário, escrevemos o código de P no arquivo de saída, adicionamos a concatenação de P com o byte lido no dicionário com o próximo código disponível e a palavra P passa a conter apenas o byte lido. 

Essa iteração segue até o último byte, momento em que precisamos garantir que a última palavra também seja escrita no arquivo de saída.


### Descompressor.py

A descompressão de arquivos é feita pelo script "descompressor.py". Que deve ser utilizado da seguinte forma:

```{sh}
python3 descompressor.py arquivo_entrada.lzw
```

Se o nome do arquivo de saída não for especificado, ele é gerado automaticamente com a extensão _descomprimido adicionada antes da extensão original.

O dicionário é inicializado com todos os 256 valores possíveis que um byte pode armazenar (0 a 255). Cada valor é inserido na Trie e mapeado para sua sequência correspondente.

O arquivo de entrada é aberto para leitura em modo binário. O primeiro byte é lido para determinar o número de bits utilizado para os códigos. Os códigos são lidos sequencialmente do arquivo comprimido e armazenados em uma lista.

Para cada código lido, a sequência de bytes correspondente é recuperada do dicionário. Se um código não estiver no dicionário, ele é tratado como um caso especial e a sequência é gerada dinamicamente. A sequência de bytes correspondente é escrita no arquivo de saída. Novas sequências são adicionadas ao dicionário à medida que os códigos são processados.

O arquivo de saída é aberto para escrita em modo binário. As sequências de bytes decodificadas são escritas no arquivo de saída.


# Exemplos de Funcionamento

## Compressão de Texto
Suponha que temos um arquivo de texto exemplo.txt com o seguinte conteúdo:

ABABABA

A iteração funcionaria da seguinte maneira:

1. **Primeiro byte (A)**:
   - Palavra Atual (A) está no dicionário.

2. **Segundo byte (B)**:
   - Palavra Atual (AB) não está no dicionário.
   - AB é adicionado à Trie com o próximo código possível (256).
   - Palavra Atual -> (B).

3. **Terceiro byte (A)**:
   - Palavra Atual (BA) não está no dicionário.
   - BA é adicionado à Trie com o próximo código possível (257).
   - Palavra Atual -> (A).

4. **Quarto byte (B)**:
   - Palavra atual (AB) está no dicionário.

5. **Quinto byte (A)**:
   - Palavra atual (ABA) não está no dicionário.
   - ABA é adicionado à Trie com o próximo código possível (258).
   - Palavra Atual -> (A).

6. **Sexto byte (B)**:
   - Palavra atual (AB) está no dicionário.

7. **Sétimo byte (A)**:
   - Palavra atual (ABA) está no dicionário.
  

O arquivo comprimido conterá os códigos binários correspondentes:

65 66 256 258

## Descompressão do texto

Durante a compressão, os dados não são armazenados como a sequência original de bytes (`ABABABA`). Em vez disso, são armazenados como códigos que representam as sequências de bytes encontradas no dicionário. Esses códigos são escritos no arquivo comprimido em formato binário.

Vamos considerar o exemplo do texto `ABABABA` e ver como ele é representado no arquivo comprimido:

1. **Primeiro byte (A)**:
   - Palavra Atual (A) está no dicionário.
   - Continua para o próximo byte.

2. **Segundo byte (B)**:
   - Palavra Atual (AB) não está no dicionário.
   - Escreve o código de `A` (65) no arquivo de saída.
   - Adiciona `AB` ao dicionário com o próximo código disponível (256).
   - Palavra Atual -> (B).

3. **Terceiro byte (A)**:
   - Palavra Atual (BA) não está no dicionário.
   - Escreve o código de `B` (66) no arquivo de saída.
   - Adiciona `BA` ao dicionário com o próximo código disponível (257).
   - Palavra Atual -> (A).

4. **Quarto byte (B)**:
   - Palavra Atual (AB) está no dicionário.
   - Continua para o próximo byte.

5. **Quinto byte (A)**:
   - Palavra Atual (ABA) não está no dicionário.
   - Escreve o código de `AB` (256) no arquivo de saída.
   - Adiciona `ABA` ao dicionário com o próximo código disponível (258).
   - Palavra Atual -> (A).

6. **Sexto byte (B)**:
   - Palavra Atual (AB) está no dicionário.
   - Continua para o próximo byte.

7. **Sétimo byte (A)**:
   - Palavra Atual (ABA) está no dicionário.
   - Escreve o código de `ABA` (258) no arquivo de saída.
  
Durante a descompressão, o algoritmo lê esses códigos binários e reconstrói as sequências de bytes originais usando o dicionário que é reconstruído dinamicamente.

1. **Primeiro Código (65)**:
   - Código: `65`
   - `65` está no dicionário.
   - Escreve `A` no arquivo de saída.
   - Palavra atual (`W`): `A`

2. **Segundo Código (66)**:
   - Código: `66`
   - `66` está no dicionário.
   - Escreve `B` no arquivo de saída.
   - Adiciona `AB` ao dicionário com o próximo código disponível (256).
   - Palavra atual (`W`): `B`

3. **Terceiro Código (256)**:
   - Código: `256`
   - `256` está no dicionário.
   - Escreve `AB` no arquivo de saída.
   - Adiciona `BA` ao dicionário com o próximo código disponível (257).
   - Palavra atual (`W`): `AB`

4. **Quarto Código (258)**:
   - Código: `258`
   - `258` está no dicionário.
   - Escreve `ABA` no arquivo de saída.
   - Adiciona `ABA` ao dicionário com o próximo código disponível (258).
   - Palavra atual (`W`): `ABA`


## Análise
